# render.yaml

services:
  - type: web
    name: tokenization-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FIREBASE_CRED_PATH
        value: serviceAccountKey.json
